name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy to production using ssh
      uses: appleboy/ssh-action@v0.0.9
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/falghifa/public_html/
          git remote remove origin
          git remote add origin git@github.com:falghi/website-portfolio.git
          ls -al ~/.ssh
          cat ~/.ssh/id_rsa.pub
          git pull
          git branch --set-upstream-to=origin/master master
          git pull
